Fixed build break w/ gcc-4.6.3 on Ubuntu 12.04
 [Problem] perfect.c:626:7: error: too many arguments to function ‘malloc’
   [Cause] There were too many arguments
[Solution] Fixed error